// 步驟1:約束 (先單獨執行這一檔)
CREATE CONSTRAINT part_code IF NOT EXISTS FOR (n:Part) REQUIRE n.code IS UNIQUE;
CREATE CONSTRAINT chapter_code IF NOT EXISTS FOR (n:Chapter) REQUIRE n.code IS UNIQUE;
CREATE CONSTRAINT section_code IF NOT EXISTS FOR (n:Section) REQUIRE n.code IS UNIQUE;
CREATE CONSTRAINT article_code IF NOT EXISTS FOR (n:Article) REQUIRE n.code IS UNIQUE;
CREATE CONSTRAINT paragraph_code IF NOT EXISTS FOR (n:Paragraph) REQUIRE n.code IS UNIQUE;
CREATE CONSTRAINT subparagraph_code IF NOT EXISTS FOR (n:Subparagraph) REQUIRE n.code IS UNIQUE;
